name: Build and Release Arch Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Arch Linux
      run: sudo docker run --name arch-container -d -t archlinux:latest /bin/bash

    - name: Update package database in container
      run: docker exec -t arch-container pacman -Syu --noconfirm

    - name: Install required packages for building
      run: docker exec -t arch-container pacman -S --noconfirm base-devel pacman-contrib

    - name: Copy repository files to container
      run: docker cp . arch-container:/home/build/

    - name: Change ownership of build directory
      run: docker exec -t arch-container chown -R nobody:nobody /home/build

    - name: Install package dependencies
      run: docker exec -t arch-container pacman -S --noconfirm kubelet kubeadm crio crun open-iscsi nfs-utils libcrossguid nvme-cli

    - name: Build the package
      run: docker exec -t arch-container su nobody -s /bin/bash -c "cd /home/build && makepkg -s"
      
    - name: Generate package signature
      run: docker exec -t arch-container su nobody -s /bin/bash -c "cd /home/build && gpg --batch --gen-key key-config && gpg --detach-sign *.pkg.tar.zst"

    - name: Retrieve built package and signature
      run: docker cp arch-container:/home/build/. .

    - name: Upload package as release artifact
      uses: actions/upload-artifact@v3
      with:
        name: arch-package
        path: |
          *.pkg.tar.zst
          *.pkg.tar.zst.sig
